theme = "nord"

[editor]
line-number = "relative"
shell = ["bash", "-c"]
cursorline = true
rulers = [80, 120]
mouse = true
auto-pairs = false
color-modes = true
true-color = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
tab = "all"

[editor.indent-guides]
render = true

[keys.normal]
"*" = [
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "search_next",
]
"#" = [
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "search_prev",
]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[keys.normal.space.C-c]
"f" = ["file_picker_in_current_buffer_directory"]
